# Generated by Django 2.2.12 on 2020-04-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('netid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('identity', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='professorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
    ]
