# Generated by Django 3.0.3 on 2020-04-01 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='netid',
            field=models.CharField(default='defaultNetid', max_length=20),
        ),
    ]
