# Generated by Django 3.0.3 on 2020-04-01 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_identity_netid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identity',
            name='netid',
            field=models.CharField(max_length=20),
        ),
    ]
